---
app:
  node: um
  domain: ldp.herculesasioizertis.desa.um.es
  subdomain: um
  language: en-EN
  threadsInLod: 20
  defaultSchema: http://$domain$/$sub-domain$/$language$/$type$/$reference$/$concept$
  uris-factory-host: http://uris-generator:8080/
  discovery-service-host: http://herc-iz-front-desa.atica.um.es:8089/
  service-data-name: Federation

  persistence:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      username: app
      password: sqlpass
      url: jdbc:mariadb://127.0.0.1:3307/discovery?ssl=false&createDatabaseIfNotExist=true
    jpa:
      dialect: org.hibernate.dialect.MariaDB53Dialect
      generate-ddl: true
      ddl-auto: update
      show-sql: true
      format_sql: true
      use_sql_comments: true
      properties:
        hibernate.temp.use_jdbc_metadata_defaults: false
  # CORS
  cors:
    enabled: true
    allowedOrigin: '*'
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders:
      - Authorization
      - X-Requested-With
      - Content-Type
    maxAge: 3600

  # Cache configuration
  cache:
    embedded:
      enabled: true

  # Swagger
  swagger:
    enabled: true

  # Trellis
  trellis:
    enabled: true
    endpoint: http://localhost:80
    authentication:
      enabled: false
      username: admin
      password: admin

data:
  readCacheFromFirebase: false
  elasticsearch:
    host: herc-iz-bd-desa.atica.um.es
    port: 9200
  redis:
    host: herc-iz-bd-desa.atica.um.es
    port: 16379
    password: j!VxttMdHGhy
  kafka:
    host: localhost
    port: 9092
    topicEntityChange:
      topic: entity_change
      groupId: entity_change_1
    topicDiscoveryAction:
      topic: discovery_action
      groupId: discovery_action_1

data-sources:
  useCachedData: true
  thresholds:
    elasticSearchAttributesThresholdSimple: 0.8
    elasticSearchAttributesNumberRatioSimple: 0.4
    elasticSearchAttributesThresholdComplex: 0.5
    elasticSearchAttributesNumberRatioComplex: 0.2
    elasticSearchMaxDesirableNumbersOfResults: 50
    elasticSearchCutOffAccordPercentile: 0.5
    manualThreshold: 0.7
    automaticThreshold: 0.95
    manualThresholdWithOutId: 0.7
    automaticThresholdWithOutId: 0.95
    urisFactoryHost: http://uris-generator:8080/
    discoveryServiceHost: http://herc-iz-front-desa.atica.um.es:8089/
    serviceDataName: Federation
#  nodes:
#    -
#      nodeName: um
#      serviceName: sparql-proxy
#      tripleStores:
#        -
#          type: sparql
#          baseURL: http://localhost:9328/
#          name: sparql
#          user:
#          password:
#
#    -
#      nodeName: um2
#      serviceName: sparql-proxy
#      tripleStores:
#        -
#          type: sparql
#          baseURL: http://localhost:9328/
#          name: sparql
#          user:
#          password:

# LOD
lod:
  host: http://localhost
  port: 9328
  endpoint: /lod/search
  lodDatasets:
    - CROSSREF,SCOPUS,WIKIDATA,ORCID,DOAJ,PUBMED,DBLP

## Actuator
management:
  security:
    enabled: false
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  server:
    port: 9321
  health:
    mail:
      enabled: false
    ldap:
      enabled: false
    redis:
      enabled: false

## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}

logging:
  level:
    org.hibernate.SQL: INFO
    #org.hibernate.type: TRACE

spring:
  security:
    enabled: false
  data:
    elasticsearch:
      cluster-name: es-asio-cluster
      cluster-nodes: localhost:9300
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
security:
  basic:
    enabled: false