---
app:
  # Swagger
  swagger:
    enabled: true
    secured: false
    authServerUrl: ../oauth
    authServerClientId: acme
    authServerClientSecret: acmesecret
## Actuator
management:
  health:
    redis:
      enabled: false
  server:
    port: 9327

server:
    port: 9327

data:
  kafka:
    host: localhost
    port: 9092