---
app:
  # Swagger
  swagger:
    enabled: true
    secured: false
    authServerUrl: ../oauth
    authServerClientId: acme
    authServerClientSecret: acmesecret
## Actuator
management:
  health:
    redis:
      enabled: false
  server:
    port: 9327

server:
    port: 9327
## Data sources      
data-sources:
  nodes:
    -
      nodeName: um
      tripleStores:
        -
          type: trellis
          baseURL: http://herc-iz-front-desa.atica.um.es/
          user: admin
          password: admin

#    - nodeName: um2
#      tripleStores:
#        - type: trellis
#          baseURL: http://localhost:80/
#          user: admin
#          password: admin
data:
  kafka:
    host: localhost
    port: 9092