---
app:
  persistence:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      username: app
      password: sqlpass
      url: jdbc:mariadb://127.0.0.1:3307/discovery?ssl=false&createDatabaseIfNotExist=true
    jpa:
      dialect: org.hibernate.dialect.MariaDB53Dialect
      generate-ddl: true
      ddl-auto: create
      show-sql: true
      format_sql: true
      use_sql_comments: true
      properties:
        hibernate.temp.use_jdbc_metadata_defaults: false
  # CORS
  cors:
    enabled: true
    allowedOrigin: '*'
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders:
      - Authorization
      - X-Requested-With
      - Content-Type
    maxAge: 3600

  # Cache configuration
  cache:
    embedded:
      enabled: true

  # Swagger
  swagger:
    enabled: true

data:
  readCacheFromFirebase: false
  elasticsearch:
    host: localhost
    port: 9200
  redis:
    host: localhost
    port: 16379
    password: redispass
  kafka:
    host: localhost
    port: 9092
    topicEntityChange:
      topic: entity_change
      groupId: entity_change_1
    topicDiscoveryAction:
      topic: discovery_action
      groupId: discovery_action_1

data-sources:
  useCachedData: true
  thresholds:
    elasticSearchAttributesThresholdSimple: 0.8
    elasticSearchAttributesNumberRatioSimple: 0.4
    elasticSearchAttributesThresholdComplex: 0.5
    elasticSearchAttributesNumberRatioComplex: 0.2
    elasticSearchMaxDesirableNumbersOfResults: 50
    elasticSearchCutOffAccordPercentile: 0.5
    manualThreshold: 0.7
    automaticThreshold: 0.95
  nodes:
    -
      nodeName: um
      tripleStores:
        -
          type: trellis
          baseURL: http://herc-iz-front-desa.atica.um.es/
          user: admin
          password: admin

#    - nodeName: um2
#      tripleStores:
#        - type: trellis
#          baseURL: http://localhost:80/
#          user: admin
#          password: admin

## Actuator
management:
  security:
    enabled: false
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  server:
    port: 9321
  health:
    mail:
      enabled: false
    ldap:
      enabled: false
    redis:
      enabled: false

## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}

logging:
  level:
    org.hibernate.SQL: DEBUG
    #org.hibernate.type: TRACE

spring:
  security:
    enabled: false
  data:
    elasticsearch:
      cluster-name: es-asio-cluster
      cluster-nodes: localhost:9300

security:
  basic:
    enabled: false