---
app:
  node: um
  domain: ldpld1.um.es
  subdomain: um
  language: en-EN
  threadsInLod: 10
  defaultSchema: https://$domain$/$sub-domain$/$language$/$type$/$concept$/$reference$
  uris-factory-host: https://localhost:9321/
  discovery-service-host: http://localhost:9329/
  service-data-name: Federation

  persistence:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      username: app
      password: sqlpass
      url: jdbc:mariadb://127.0.0.1:3307/discovery?ssl=false&createDatabaseIfNotExist=true&UseUnicode=true&characterEncoding=utf8
    jpa:
      dialect: org.hibernate.dialect.MariaDB53Dialect
      generate-ddl: true
      ddl-auto: create
      show-sql: true
      format_sql: false
      use_sql_comments: false
      properties:
        hibernate:
          temp.use_jdbc_metadata_defaults: false
          jdbc.time_zone: UTC
  # CORS
  cors:
    enabled: true
    allowedOrigin: '*'
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders:
      - Authorization
      - X-Requested-With
      - Content-Type
    maxAge: 3600

  # Cache configuration
  cache:
    embedded:
      enabled: true

  # Swagger
  swagger:
    enabled: true

  # Trellis
  trellis:
    enabled: true
    endpoint: http://localhost:80
    authentication:
      enabled: false
      username: admin
      password: admin

data:
  readCacheFromFirebase: false
  elasticsearch:
    host: localhost
    port: 9200
  redis:
    host: localhost
    port: 16379
    password: j!VxttMdHGhy
  kafka:
    host: localhost
    port: 9092
    topicEntityChange:
      topic: entity_change
      groupId: entity_change_1
    topicDiscoveryAction:
      topic: discovery_action
      groupId: discovery_action_1

data-behaviour:
  behaviours:
    - className: Conference
      ignoreLinks:
        - presents
    - className: Article
      ignoreLinks:
        - correspondingAuthor
    - className: Publication
      ignoreLinks:
        - correspondingAuthor
    - className: Patent
      ignoreLinks:
        - correspondingAuthor
    - className: Center
      ignoreLinks:
        - relatedBy
    - className: Department
      ignoreLinks:
        - relatedBy
    - className: Organization
      ignoreLinks:
        - relatedBy
    - className: Doctoral-thesis
      ignoreLinks:
        - correspondingAuthor
    - className: Person
      ignoreLinks:
        - hasCV
    - className: Project
      ignoreLinks:
        - relates
        - hasKnowledgeArea
    - className: Research-line
      ignoreLinks:
        - relates
    - className: Research-line
      ignoreLinks:
        - relates
data-sources:
  useCachedData: true
  thresholds:
    elasticSearchAttributesThresholdSimple: 0.8
    elasticSearchAttributesNumberRatioSimple: 0.4
    elasticSearchAttributesThresholdComplex: 0.5
    elasticSearchAttributesNumberRatioComplex: 0.2
    elasticSearchMaxDesirableNumbersOfResults: 50
    elasticSearchCutOffAccordPercentile: 0.5
    manualThreshold: 0.75
    automaticThreshold: 0.95
    manualThresholdWithOutId: 0.85
    automaticThresholdWithOutId: 0.98
  urisFactoryHost: http://localhost:9326/
  discoveryServiceHost: http://localhost:9329/
  serviceDataName: Federation

datahandler:
  ingnoredLinks:
    - className: Conference
      attributes:
        - presents

#  nodes:
#    -
#      nodeName: um
#      serviceName: sparql-proxy
#      tripleStores:
#        -
#          type: sparql
#          baseURL: http://localhost:9328/
#          name: sparql
#          user:
#          password:
#
#    -
#      nodeName: um2
#      serviceName: sparql-proxy
#      tripleStores:
#        -
#          type: sparql
#          baseURL: http://localhost:9328/
#          name: sparql
#          user:
#          password:

# LOD
lod:
  host: http://localhost
  port: 9328
  endpoint: /lod/search
  lodDatasets:
    - CROSSREF,SCOPUS,WIKIDATA,ORCID,DOAJ,PUBMED,DBLP

## Actuator
management:
  security:
    enabled: false
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  server:
    port: 9327
  health:
    mail:
      enabled: false
    ldap:
      enabled: false
    redis:
      enabled: false

## In case of configure web endpoints, remove it or change port number
server:
  port: ${management.server.port}
  error:
    whitelabel:
      enabled: false

#logging:
#  level:
    # org.hibernate.SQL: debug
    # org.hibernate.type: trace

spring:
  datasource:
    testOnBorrow: true
  security:
    enabled: false
  data:
    elasticsearch:
      cluster-name: es-asio-cluster
      cluster-nodes: localhost:9300
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
  mail:
    host: smtp.gmail.com
    port: 587
    username: herculesizertis@gmail.com
    password: h3rcul3s1z3rt1s
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

security:
  basic:
    enabled: false

hierarchy:
  hierarchies:
    - className: Center
      parentClassName: Organization
