version: '3.1'

services:
  db:
    image: mariadb:10.3
    container_name: mariadb_asio
    restart: unless-stopped
    ports:
      #      - "3306:3306"
      - "3307:3306"
    volumes:
      - mysql-data2:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      # MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: 'discovery'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'sqlpass'
    networks:
      default:
        aliases:
          - mysql.svc
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch_asio
    restart: unless-stopped
    environment:
      - cluster.name=es-asio-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    container_name: kibana_asio
    restart: unless-stopped
    image: docker.elastic.co/kibana/kibana:6.5.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  redis:
    container_name: redis_asio
    restart: unless-stopped
    image: "bitnami/redis:latest"
    ports:
      - "16379:6379"
    environment:
      - REDIS_PASSWORD=redispass
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      default:
        aliases:
          - redis.svc
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper_asio
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    depends_on:
      - db
      - elasticsearch
      - redis
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka_asio
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
volumes:
  mysql-data2:
  redis-data:
  elasticsearch-data:
    driver: local