version: '3.1'

services:
  fuseki-sandbox:
    build: ./fuseki-tdb/
    container_name: fuseki-asio
    restart: always
    environment:
      - ADMIN_PASSWORD=pw123
    ports:
      - "3030:3030"
    volumes:
      - fuseki-data-sandbox:/fuseki/databases/trellis
      - fuseki-backup-sandbox:/fuseki/databases/backups
      #- ./fuseki-conf/config.ttl:/fuseki/config.ttl
      #- ./fuseki-conf/trellis.ttl:/fuseki/trellis.ttl
      #- ./fuseki-conf/shiro.ini:/fuseki/shiro.ttl
      #- ./fuseki-conf/log4j.properties:/fuseki/log4j.properties
    networks:
      - sandbox-net
volumes:
  fuseki-data-sandbox:
  fuseki-backup-sandbox:
  trellis-data:
  trellis-log:

networks:
  sandbox-net: