version: '3.1'

services:
  fuseki-sandbox:
    build: ./fuseki-tdb/
    container_name: fuseki-asio
    restart: always
    environment:
      - JVM_ARGS=-Xmx4g
      - ADMIN_PASSWORD=pw123
    ports:
      - "3030:3030"
    volumes:
      - fuseki-data-sandbox:/fuseki/databases/trellis
      - fuseki-backup-sandbox:/fuseki/databases/backups
      #- ./fuseki-conf/config.ttl:/fuseki/config.ttl
      #- ./fuseki-conf/trellis.ttl:/fuseki/trellis.ttl
      #- ./fuseki-conf/shiro.ini:/fuseki/shiro.ttl
      #- ./fuseki-conf/log4j.properties:/fuseki/log4j.properties
    networks:
      - sandbox-net
  trellis:
    build: ./trellis
    container_name: trellis
    ports:
      - "80:8080"
    links:
      - "fuseki-sandbox:fuseki-sandbox"
    depends_on:
      - fuseki-sandbox
    volumes:
      - trellis-data:/opt/trellis/data
      - trellis-log:/opt/trellis/log
    networks:
      - sandbox-net

volumes:
  fuseki-data-sandbox:
  fuseki-backup-sandbox:
  trellis-data:
  trellis-log:

networks:
  sandbox-net: